name: Build My Apps

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  # تحديث بسيط (Shorebird)
  patch:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Format code
        run: dart format .

      - name: Setup Shorebird
        uses: shorebirdtech/setup-shorebird@v1

      - name: Create Shorebird Patch
        run: shorebird patch android
        env:
          SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}

  # تحديث كبير (Google Play)
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Format code
        run: dart format .

      - name: Build App Bundle
        run: flutter build appbundle --release

      - name: Upload to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ secrets.GOOGLE_PLAY_JSON_KEY }}
          packageName: com.hodaelnas.hodaelnas
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: internal